cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    qschevenhoven:
      email: quirijn.schevenhoven@confano.nl
      failed_login_attempts: 0
      logged_in: false
      name: Quirijn Schevenhoven
      password: $2b$12$Enkpf9J3nKLQAeNmHb7aa.qIeLY725uGAW2FIvYYAhWE1k8ftm0xu
preauthorized:
  emails:
  #- melsby@gmail.com