cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    qschevenhoven:
      email: quirijn.schevenhoven@cofano.nl
      failed_login_attempts: 0
      logged_in: false
      name: Quirijn Schevenhoven
      password: $2b$12$PHbxjyLg4d5uvRzdshl.aOm2yi3aMMif0CthL0RluuC/v3HoE4c8S
    flandheer:
      email: frank.landheer@cofano.nl
      failed_login_attempts: 0
      logged_in: false
      name: Frank Landheer
      password: $2b$12$NNm3nzYcSlneicXP6YdukuUfWstUi2WpmJ4SqI7kO7im3E8HYuR9C
    imaessen:
      email: i.maessen@dilog.nl
      failed_login_attempts: 0
      logged_in: false
      name: Iwan Maessen
      password: $2b$12$rt612L.hvdr0SrMVd8e/Hu2P1UJgaVDAYkwwPoBKchcC0VQU6iwiO
    jroc:
      email: john@roc.nl
      failed_login_attempts: 0
      logged_in: false
      name: John ROC Waalwijk
      password: $2b$12$B1ii3n0LDy5gxy6Sk4xS7eeXUgBbuEXPmS16l5hKykL2mphXN/TGu
preauthorized:
  emails:
  #- melsby@gmail.com